//ROW TYPES
const HEADER = "HEADER";
const QUESTION_ROW = "QUESTION_ROW";
const DESCRIPTIVE_ROW = "DESCRIPTIVE_ROW";

//QUESTION ROW SELECTION TYPES
const SINGLE_SELECTION = "SINGLE_SELECTION";
const LONG_ANSWER = "LONG_ANSWER";
const DEFAULT = "DEFAULT";

//PLACEHOLDERS
const DESCRIPTIVE_ROW_PLACEHOLDER = "Type descriptive row here";
const TYPE_HEADER_HERE = "Type header here";
const HEADER_PLACEHOLDER = "header";
const QUESTION_PLACEHOLDER = "Question";
const VALUE_PLACEHOLDER = "Value";
const TYPE_QUESTION_HERE = "type question here";

export {
    HEADER,
    QUESTION_ROW,
    DESCRIPTIVE_ROW,
    SINGLE_SELECTION,
    LONG_ANSWER,
    DEFAULT,
    DESCRIPTIVE_ROW_PLACEHOLDER,
    TYPE_HEADER_HERE,
    HEADER_PLACEHOLDER,
    QUESTION_PLACEHOLDER,
    VALUE_PLACEHOLDER,
    TYPE_QUESTION_HERE
}